version: "3.5"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/jeluiz4/inception/srcs/requirements/wordpress/dump/
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/jeluiz4/inception/srcs/requirements/mariadb/dump/
                        o: bind
                        type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    ports:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    ports:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
